apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-iuna
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/susdas_quay_org/mvp-dev-fdtw-tenant/mvp-test-app/test-mvp-component-iuna@sha256:d47ea8c6ebfcc5108ecad45843182af5f36a328c10676bb297caee7ae2bbf45d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
